[project]
name = "challonge-notifier-bot"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytelegrambotapi>=4.27.0",
    "requests>=2.32.3",
]
