[project]
name = "challonge-notifier-bot"
version = "0.2.0"
description = "Simple challonge TG bot for notifications about matches"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytelegrambotapi>=4.27.0",
    "requests>=2.32.3",
]
